"use client";
// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Inicio",
//   description: "Generated by create next app",
// };
import { Button } from "@/components/ui/button";
import Layout from "./Layout";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../store/store";
import { decrement, increment, incrementByAmount } from "../store/slices/counter/counterSlice";
import { useSession } from "next-auth/react";
import SwiperStyle from "./components/SwiperStyle";
import { Splide, SplideSlide } from '@splidejs/react-splide';
import '@splidejs/react-splide/css';

import { useSwiper } from "../hooks/useSwiper";
import { SplideOptions } from "@/types/libraries";

export default function HomePage() {
  const { data: session } = useSession()
  console.log(session);

  console.log(session?.user.rol);
  const { value } = useSelector((state: RootState) => state.counter);
  const dispatch = useDispatch();

  console.log();
  const swiperDataGenres = useSwiper({ type: 'genre' });
  const swiperDataCategories = useSwiper({ type: 'category' });
  const phrasesData: string[] = [
    "Diseñada para moverte contigo",
    "Estilo que se siente",
    "La moda hecha a tu medida",
    "Tu esencia, tu look",
    "Comodidad sin perder la onda",
    "Llevá tu estilo a otro nivel",
    "Ropa que habla por ti",
    "Hecha para tu día a día"
  ];

  // Configuración de Splide
  const splideOptions: SplideOptions = {
    type: 'loop',
    autoplay: true,
    interval: 1,
    speed: 15000,
    easing: 'linear',
    arrows: false,
    pagination: false,
    drag: true,

    perPage: 4,
    perMove: 1,
    gap: '4rem',

    resetProgress: false,
    rewind: false,           // Sin rebobinado
    waitForTransition: false, // No espera a que termine la transición
    updateOnMove: true,      // Actualiza durante el movimiento
    breakpoints: {
      768: {
        perPage: 2,
        speed: 12000,
        gap: '3rem',
      },
      480: {
        perPage: 1,
        speed: 10000,
        gap: '2rem',
      },
    },
  };

  return (

    <>
      <Layout>
        <div className="flex items-center justify-center py-16 px-8 md:py-20 md:px-32 lg:py-32 bg-[url('../public/hero-image-two.webp')] bg-cover bg-center w-full xl:h-lvh">
          <div className="max-w-7xl text-center xl:px-40">
            <h1 className="text-[#ffffff] text-4xl md:text-5xl lg:text-6xl font-bold ">Diseños modernos, Estilos personalizados

            </h1>
            {/* <p className="text-white font-bold mt-8 mb-7">
              Descubre nuestra colección de productos diseñados para ti
            </p> */}
            <Button className="w-48 px-10  bg-purple-700 hover:bg-purple-600 cursor-pointer mt-12 ">
              <p className="text-xl ">Compra ahora</p>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-arrow-right ml-2 mt-1 h-4 w-4" data-lov-id="src/components/HeroSection.tsx:23:16" data-lov-name="ArrowRight" data-component-path="src/components/HeroSection.tsx" data-component-line="23" data-component-file="HeroSection.tsx" data-component-name="ArrowRight" data-component-content="%7B%22className%22%3A%22ml-2%20h-4%20w-4%22%7D"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path>
              </svg>
            </Button>

          </div>

        </div>
        <div className="w-full flex py-10 md:pt-20 px-16 justify-center ">

          <div className="max-w-7xl  grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="rounded-lg border dark:border-yellow-300 transition-all duration-300 hover:shadow-md dark:hover:shadow-yellow-300 py-7 ps-5 pe-4">
              <div className="rounded-full bg-yellow-100 dark:bg-yellow-300 h-12 w-12 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-truck h-6 w-6 dark:text-black " data-lov-id="src/components/BenefitsSection.tsx:38:16" data-lov-name="benefit.icon" data-component-path="src/components/BenefitsSection.tsx" data-component-line="38" data-component-file="BenefitsSection.tsx" data-component-name="benefit.icon" data-component-content="%7B%22className%22%3A%22h-6%20w-6%22%7D"><path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2"></path><path d="M15 18H9"></path><path d="M19 18h2a1 1 0 0 0 1-1v-3.65a1 1 0 0 0-.22-.624l-3.48-4.35A1 1 0 0 0 17.52 8H14"></path><circle cx="17" cy="18" r="2"></circle><circle cx="7" cy="18" r="2"></circle>
                </svg>
              </div>
              <div className="mt-3">
                <h3 className="font-medium text-xl mb-3"> Envios </h3>
                <p> Nuestro equipo esta listo para ayudarte con tus pedidos</p>
              </div>
            </div>
            <div className="rounded-lg border dark:border-red-400 transition-all duration-300 hover:shadow-md  dark:hover:shadow-red-400 py-7 ps-5 pe-0">
              <div className="rounded-full bg-red-100 dark:bg-red-400 h-12 w-12 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-refresh-cw h-6 w-6 dark:text-black" data-lov-id="src/components/BenefitsSection.tsx:38:16" data-lov-name="benefit.icon" data-component-path="src/components/BenefitsSection.tsx" data-component-line="38" data-component-file="BenefitsSection.tsx" data-component-name="benefit.icon" data-component-content="%7B%22className%22%3A%22h-6%20w-6%22%7D"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path><path d="M21 3v5h-5"></path><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"></path><path d="M8 16H3v5"></path></svg>
              </div>
              <div className="mt-3">

                <h3 className="font-medium text-xl mb-3"> Retornos </h3>
                <p> Los artículos son de venta final</p>
              </div>
            </div>
            <div className="rounded-lg border dark:border-green-400 transition-all duration-300 hover:shadow-md dark:hover:shadow-green-400 py-7 ps-5 pe-4">
              <div className="rounded-full bg-green-100 dark:bg-green-400 h-12 w-12 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-shield-check h-6 w-6 dark:text-black" data-lov-id="src/components/BenefitsSection.tsx:38:16" data-lov-name="benefit.icon" data-component-path="src/components/BenefitsSection.tsx" data-component-line="38" data-component-file="BenefitsSection.tsx" data-component-name="benefit.icon" data-component-content="%7B%22className%22%3A%22h-6%20w-6%22%7D"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path><path d="m9 12 2 2 4-4"></path></svg>
              </div>
              <div className="mt-3">

                <h3 className="font-medium text-xl mb-3"> Garantia de calidad </h3>
                <p> Cada producto cumple con nuestros altos estándares.</p>
              </div>
            </div>
            <div className="rounded-lg border dark:border-blue-400 transition-all duration-300 hover:shadow-md dark:hover:shadow-blue-400 py-7 ps-5 pe-4">
              <div className="rounded-full bg-blue-100 dark:bg-blue-400 h-12 w-12 flex items-center justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-credit-card h-6 w-6 dark:text-black" data-lov-id="src/components/BenefitsSection.tsx:38:16" data-lov-name="benefit.icon" data-component-path="src/components/BenefitsSection.tsx" data-component-line="38" data-component-file="BenefitsSection.tsx" data-component-name="benefit.icon" data-component-content="%7B%22className%22%3A%22h-6%20w-6%22%7D"><rect width="20" height="14" x="2" y="5" rx="2"></rect><line x1="2" x2="22" y1="10" y2="10"></line></svg>
              </div>
              <div className="mt-3">

                <h3 className="font-medium text-xl mb-3"> Pagos seguros </h3>
                <p> Su información de pago siempre está segura </p>
              </div>
            </div>
          </div>

        </div>
        <SwiperStyle
          title="Nuevos en llegar"
          dataTitle={swiperDataGenres.dataGenres}
          dataBody={swiperDataGenres} // Pasa todo el hook, no solo los productos
        />

        <div className="flex flex-col justify-center items-center">
          {value}
          <button className="mb-4 p-4  bg-red-300" onClick={() => dispatch(increment())}>
            +1
          </button>
          <button className="mb-4 p-4  bg-blue-300" onClick={() => dispatch(decrement())}>
            -1
          </button>
          <button className="mb-4 p-4  bg-green-300" onClick={() => dispatch(incrementByAmount(value))}>
            increment by value
          </button>
        </div>
        <div className="relative min-h-[400px] md:min-h-screen bg-[url('../public/find-your-fit-mobile.webp')] lg:bg-[url('../public/find-your-fit.webp')] bg-cover bg-center bg-no-repeat lg:mb-10">

          <div className="absolute inset-0 bg-black/20"></div>
          <div className="relative z-10 flex items-center min-h-screen px-6 sm:px-8 lg:px-12">
            <div className="max-w-lg">

              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
                Descubre la prenda que mejor te queda.
              </h1>


              <p className="text-lg sm:text-xl text-white mb-8 leading-relaxed">
                Diseños únicos, pensados para ti. Elige tu estilo y marca la diferencia.
              </p>


              <div className="flex flex-col sm:flex-row gap-4">
                <button className="bg-transparent border-2 border-white text-white font-semibold py-3 px-8 text-sm tracking-wider uppercase hover:bg-white hover:text-black transition-all duration-300 cursor-pointer">
                  SHOP HATS
                </button>
                <button className="bg-transparent border-2 border-white text-white font-semibold py-3 px-8 text-sm tracking-wider uppercase hover:bg-white hover:text-black transition-all duration-300 cursor-pointer">
                  SHOP ACCESSORIES
                </button>
              </div>
            </div>
          </div>
        </div>



        <SwiperStyle
          title="Categorías populares"
          dataTitle={swiperDataCategories.dataCategories}
          dataBody={swiperDataCategories} // Pasa todo el hook, no solo los productos
        />
        <div className="bg-[#425d4f] py-6 overflow-hidden">
          <Splide options={splideOptions}>
            {phrasesData.map((phrase, index) => (
              <SplideSlide key={index}>
                <div className="text-center px-4">
                  <h3 className="text-white text-lg md:text-xl font-medium whitespace-nowrap">
                    {phrase}
                  </h3>
                </div>
              </SplideSlide>
            ))}
          </Splide>

        </div>


        <div className="relative min-h-[400px] md:min-h-screen bg-[url('../public/best-sellers-mobile.webp')] lg:bg-[url('../public/best-sellers.webp')] bg-cover bg-center bg-no-repeat">

          <div className="absolute inset-0 bg-black/20"></div>
          <div className="relative z-10 flex items-center min-h-screen px-6 sm:px-8 lg:px-12">
            <div className="max-w-lg">

              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-white mb-6 leading-tight">
                Los más vendidos, gran impacto
              </h1>


              <p className="text-lg sm:text-xl text-white mb-8 leading-relaxed">
                Nuestros mejores productos
              </p>


              <div className="flex flex-col sm:flex-row gap-4">
                <button className="bg-transparent border-2 border-white text-white font-semibold py-3 px-8 text-sm tracking-wider uppercase hover:bg-white hover:text-black transition-all duration-300 cursor-pointer">
                  SHOP WOMENS
                </button>
                <button className="bg-transparent border-2 border-white text-white font-semibold py-3 px-8 text-sm tracking-wider uppercase hover:bg-white hover:text-black transition-all duration-300 cursor-pointer">
                  SHOP MENS
                </button>
              </div>
            </div>
          </div>
        </div>

        <div className="relative bg-[#425d4f] py-16 px-6 overflow-hidden">

          <div className="absolute inset-0 opacity-30">

            <div className="absolute top-8 left-16">
              <svg width="40" height="60" viewBox="0 0 40 60" fill="none" className="text-emerald-600">
                <path d="M20 2C15 8 12 18 12 28C12 38 15 48 20 54C25 48 28 38 28 28C28 18 25 8 20 2Z" fill="currentColor" opacity="0.6" />
                <path d="M20 54L20 58" stroke="currentColor" strokeWidth="2" opacity="0.8" />
              </svg>
            </div>


            <div className="absolute top-4 right-1/4">
              <svg width="24" height="32" viewBox="0 0 24 32" fill="none" className="text-emerald-500">
                <path d="M12 2C8 8 6 14 6 20C6 26 8.5 30 12 30C15.5 30 18 26 18 20C18 14 16 8 12 2Z" fill="currentColor" opacity="0.5" />
              </svg>
            </div>

            <div className="absolute top-20 right-1/3">
              <svg width="20" height="28" viewBox="0 0 20 28" fill="none" className="text-emerald-500">
                <path d="M10 2C7 7 5 12 5 17C5 22 7 25 10 25C13 25 15 22 15 17C15 12 13 7 10 2Z" fill="currentColor" opacity="0.4" />
              </svg>
            </div>


            <div className="absolute top-12 right-20">
              <svg width="60" height="80" viewBox="0 0 60 80" fill="none" className="text-emerald-600">
                <path d="M30 5C25 12 20 25 20 40C20 55 25 68 30 75" stroke="currentColor" strokeWidth="2" opacity="0.6" />
                <path d="M25 20C20 15 15 15 12 18C10 20 10 25 15 28C20 25 25 22 25 20Z" fill="currentColor" opacity="0.4" />
                <path d="M35 35C40 30 45 30 48 33C50 35 50 40 45 43C40 40 35 37 35 35Z" fill="currentColor" opacity="0.4" />
              </svg>
            </div>


            <div className="absolute bottom-8 right-16">
              <svg width="50" height="40" viewBox="0 0 50 40" fill="none" className="text-emerald-600">
                <path d="M5 20C12 15 22 12 32 12C42 12 52 15 47 20C42 25 32 28 22 28C12 28 2 25 5 20Z" fill="currentColor" opacity="0.5" />
                <path d="M2 20L5 20" stroke="currentColor" strokeWidth="2" opacity="0.7" />
              </svg>
            </div>
          </div>


          <div className="relative w-full mx-auto px-8">
            <div className="flex flex-col lg:flex-row items-center justify-between gap-8 ">

              <div className="text-white max-w-xl">
                <h2 className="text-4xl lg:text-2xl font-bold mb-4 leading-tight">
                  Crea una cuenta para compras más rápidas  
                </h2>
                <p className="text-emerald-100 text-lg lg:text-sm opacity-90">
                  Ingresa y recibe promociones u ofertas especiales
                </p>
              </div>


              <div className="flex flex-col sm:flex-row gap-4 shrink-0">
                <button className="bg-transparent border-2 border-white text-white font-semibold py-3 px-8 text-sm tracking-wider uppercase hover:bg-white hover:text-black transition-all duration-300 cursor-pointer">
              Crear cuenta
            </button>
              </div>
            </div>
          </div>
        </div>

      </Layout>
    </>
  )
}
